    services:
      backend:
        build: ./server
        ports:
          - "5000:5000"
        env_file:
          - ./server/.env
        environment:
          - PORT=${PORT:-5000}
      frontend:
        build: ./client
        ports:
          - "3000:80"
        depends_on:
          - backend




          